### ISSUE TITLE
烦死了

### ISSUE THREAD

**Issue by 311hzr** [Korepi/Korepi-Tutorial#37]
...现在不允许加入，，已经有人开始贩卖登陆需要的码了..我是有点无语的.毕竟不能免费用了...大佬们，这样还不如直接改成卖的得了

**Comment by tedddeptrai** [comment]
invitation already opened

**Comment by 311hzr** [comment]
> 邀请已打开

啊，没赶上..可以通过赞助获得邀请吗，
